<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\DataCentresHum;
use App\Models\User;
use App\Models\UserSettings;
use App\Helpers\Helper;
use Illuminate\Support\Facades\DB;

class SendHumidityAlerts extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'alerts:humidity';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Broadcast humidity alerts';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {

       // sms server credentials
       $sms_api_base_url = "https://sms.imosys.mw";
       $sms_api_url = "smpp/api/send";
       $sms_server_key = "JBGAKHECH1MW@N0";
       //

       $humidity_records = DB::table('alerts')->where('status','pending')->where('parameter','humidity')->get();

       $Blantyre = ["AAACD0FEFF2C6A3C", "99ACD0FEFF2C6A3C"];
       $Lilongwe = ["9FACD0FEFF2C6A3C","C5ACD0FEFF2C6A3C", "88ACD0FEFF2C6A3C", "68ACD0FEFF2C6A3C"];

       foreach ( $humidity_records as $row)
       {
           $ieee = $row->ieee;
           $value = $row->value/100;

           if($ieee == "AAACD0FEFF2C6A3C" || $ieee == "99ACD0FEFF2C6A3C") {

               $title = "Centenary Bank Server Room";
               $message = "Room humidity in Blantyre data center has gone above threshold. It is currently at ".$value."%.\n\n[NOTE: IMS autogenerated message]";


                    $tokens = User::whereNotNull('firebase_token')
                        ->pluck('firebase_token')
                        ->toArray();
                    $phoneNumbers = User::whereNotNull('phone')
                        ->pluck('phone')
                        ->toArray();
                    $jsonNotification = json_encode([]); #empty for now
                    $push_api_response = Helper::PushFirebaseNotification(
                        "AAAAmNWp5RE:APA91bET4f7TdXyaXpNCiIzjp1bk7H8y8yYtJbddzhFaU13O184U5dsvwQMa0x3JPiZnhlGBXoHFGgs8wbT7TrDP7UOn8rwBJrbBwQOvq2v_uCjBg956Q9-uhh-nrZ4NgrtLnzsVhgPV", $tokens,
                        "{$title}", "{$message}",
                        $jsonNotification, "default" #sound
                    );
                    

                    //$phoneNumbers = ['+265995131052','+265994647532','+265991183117'];
                        foreach ($phoneNumbers as $phoneNumber) {
                        $sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                            'access_key' => $sms_server_key,
                            'phone' => $phoneNumber,
                            'message' => $message,
                        ));
                        }

                    /*$sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                        'access_key' => $sms_server_key,
                        'phone' => '+265994647532',
                        'message' => $message,
                    ));*/


               DB::table('alerts')->where('ieee',$ieee)->update(['status' => 'sent',]);
           
           }else {

                   $title = "Centenary Bank Server Room";
                   $message = "Room humidity in Lilongwe data center has gone above threshold. It is currently at ".$value."%.\n\n[NOTE: IMS autogenerated message]";


                        $tokens = User::whereNotNull('firebase_token')
                            ->pluck('firebase_token')
                            ->toArray();
                        $phoneNumbers = User::whereNotNull('phone')
                            ->pluck('phone')
                            ->toArray();
                        $jsonNotification = json_encode([]); #empty for now
                        $push_api_response = Helper::PushFirebaseNotification(
                            "AAAAmNWp5RE:APA91bET4f7TdXyaXpNCiIzjp1bk7H8y8yYtJbddzhFaU13O184U5dsvwQMa0x3JPiZnhlGBXoHFGgs8wbT7TrDP7UOn8rwBJrbBwQOvq2v_uCjBg956Q9-uhh-nrZ4NgrtLnzsVhgPV", $tokens,
                            "{$title}", "{$message}",
                            $jsonNotification, "default" #sound
                        );
                        

                        //$phoneNumbers = ['+265995131052','+265994647532','+265991183117'];
                            foreach ($phoneNumbers as $phoneNumber) {
                            $sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                                'access_key' => $sms_server_key,
                                'phone' => $phoneNumber,
                                'message' => $message,
                            ));
                            }

                        /*$sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                            'access_key' => $sms_server_key,
                            'phone' => '+265994647532',
                            'message' => $message,
                        ));*/

                       
                       DB::table('alerts')->where('id',$row->id)->update(['status' => 'sent',]);
                   

           }
           
       }

    }
}
