<?php

namespace App\Observers;

use App\Models\DataCentresTemp;
use App\Models\User;
use App\Helpers\Helper;
use Illuminate\Support\Facades\DB;
use App\Helpers\constants;


class TemperatureObserver
{
    /**
     * Handle the DataCentresTemp "created" event.
     *
     * @param  \App\Models\DataCentresTemp  $dataCentresTemp
     * @return void
     */
    public function created(DataCentresTemp $dataCentresTemp)
    {
        //
        $sms_api_base_url = "https://sms.imosys.mw";
        $sms_api_url = "smpp/api/send";
        $sms_server_key = "JBGAKHECH1MW@N0";

        $temperature = $dataCentresTemp->toArray();

        $temperatureInt = $temperature["value"] / 100;
        $ieee = $temperature["ieee"];
        $Blantyre = ["AAACD0FEFF2C6A3C", "99ACD0FEFF2C6A3C"];
        $Lilongwe = ["9FACD0FEFF2C6A3C","C5ACD0FEFF2C6A3C", "88ACD0FEFF2C6A3C", "68ACD0FEFF2C6A3C"];

        if($ieee == "AAACD0FEFF2C6A3C" || $ieee == "99ACD0FEFF2C6A3C") {

            if ($temperatureInt > 26) {
                $title = "Centenary Bank Server Room";
                $message = "Room temperature in Blantyre data center has gone above threshold. It is currently at {$temperatureInt}°C\n
                [NOTE: IMS autogenerated message]
                ";
                $lastAlert = DB::table('alerts')
                    ->where('location', 'Blantyre Branch')
                    ->where('parameter', 'temperature')
                    ->where('created_at', '>', now()->subHours(2))
                    ->first();

                if (!$lastAlert) {
                    $tokens = User::whereNotNull('firebase_token')
                        ->pluck('firebase_token')
                        ->toArray();

                    $phoneNumbers = User::whereNotNull('phone')
                        ->pluck('phone')
                        ->toArray();
                    $jsonNotification = json_encode([]); #empty for now
                    $push_api_response = Helper::PushFirebaseNotification(
                        "AAAAmNWp5RE:APA91bET4f7TdXyaXpNCiIzjp1bk7H8y8yYtJbddzhFaU13O184U5dsvwQMa0x3JPiZnhlGBXoHFGgs8wbT7TrDP7UOn8rwBJrbBwQOvq2v_uCjBg956Q9-uhh-nrZ4NgrtLnzsVhgPV", $tokens,
                        "{$title}", "{$message}",
                        $jsonNotification, "default" #sound
                    );
                    foreach ($phoneNumbers as $phoneNumber) {
                        $sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                            'access_key' => $sms_server_key,
                            'phone' => $phoneNumber,
                            'message' => $message,
                        ));
                    }
                    // Save the alert to the database
                    DB::table('alerts')->insert([
                        'ieee' => $ieee,
                        'parameter' => "temperature",
                        'location' => 'Blantyre Branch',
                    ]);
                }
            }
            elseif ($temperatureInt < 15) {
                $title = "Centenary Bank Server Room";
                $message = "Room temperature in Blantyre data center has gone below threshold. It is currently at {$temperatureInt}°C\n
                [NOTE: IMS autogenerated message]";
                $lastAlert = DB::table('alerts')
                    ->where('location', 'Blantyre Branch')
                    ->where('parameter', 'temperature')
                    ->where('created_at', '>', now()->subHours(1))
                    ->first();

                if (!$lastAlert) {
                    $tokens = User::whereNotNull('firebase_token')
                        ->pluck('firebase_token')
                        ->toArray();

                    $phoneNumbers = User::whereNotNull('phone')
                        ->pluck('phone')
                        ->toArray();
                    $jsonNotification = json_encode([]); #empty for now
                    $push_api_response = Helper::PushFirebaseNotification(
                        "AAAAmNWp5RE:APA91bET4f7TdXyaXpNCiIzjp1bk7H8y8yYtJbddzhFaU13O184U5dsvwQMa0x3JPiZnhlGBXoHFGgs8wbT7TrDP7UOn8rwBJrbBwQOvq2v_uCjBg956Q9-uhh-nrZ4NgrtLnzsVhgPV", $tokens,
                        "{$title}", "{$message}",
                        $jsonNotification, "default" #sound
                    );
                    foreach ($phoneNumbers as $phoneNumber) {
                        $sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                            'access_key' => $sms_server_key,
                            'phone' => $phoneNumber,
                            'message' => $message,
                        ));
                    }
                    // Save the alert to the database
                    DB::table('alerts')->insert([
                        'ieee' => $ieee,
                        'parameter' => "temperature",
                        'location' => 'Blantyre Branch',
                    ]);
                }

            }
        }
        else {
            if ($temperatureInt > 26) {
                $title = "Centenary Bank Server Room";
                $message = "Room temperature in Lilongwe data center has gone above threshold. It is currently at {$temperatureInt}°C\n
                [NOTE: IMS autogenerated message]";
                $lastAlert = DB::table('alerts')
                    ->where('location', 'Lilongwe Branch')
                    ->where('parameter', 'temperature')
                    ->where('created_at', '>', now()->subHours(2))
                    ->first();

                if (!$lastAlert) {
                    $tokens = User::whereNotNull('firebase_token')
                        ->pluck('firebase_token')
                        ->toArray();
                    $phoneNumbers = User::whereNotNull('phone')
                        ->pluck('phone')
                        ->toArray();
                    $jsonNotification = json_encode([]); #empty for now
                    $push_api_response = Helper::PushFirebaseNotification(
                        "AAAAmNWp5RE:APA91bET4f7TdXyaXpNCiIzjp1bk7H8y8yYtJbddzhFaU13O184U5dsvwQMa0x3JPiZnhlGBXoHFGgs8wbT7TrDP7UOn8rwBJrbBwQOvq2v_uCjBg956Q9-uhh-nrZ4NgrtLnzsVhgPV", $tokens,
                        "{$title}", "{$message}",
                        $jsonNotification, "default" #sound
                    );
                    foreach ($phoneNumbers as $phoneNumber) {
                        $sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                            'access_key' => $sms_server_key,
                            'phone' => $phoneNumber,
                            'message' => $message,
                        ));
                    }
                    // Save the alert to the database
                    DB::table('alerts')->insert([
                        'ieee' => $ieee,
                        'parameter' => "temperature",
                        'location' => 'Lilongwe Branch',
                    ]);
                }
            }
            elseif ($temperatureInt < 15) {
                $title = "Centenary Bank Server Room";
                $message = "Room temperature in Lilongwe data center has gone below threshold. It is currently at {$temperatureInt}°C\n
                [NOTE: IMS autogenerated message]";
                $lastAlert = DB::table('alerts')
                    ->where('location', 'Lilongwe Branch')
                    ->where('parameter', 'temperature')
                    ->where('created_at', '>', now()->subHours(2))
                    ->first();

                if (!$lastAlert) {
                    $tokens = User::whereNotNull('firebase_token')
                        ->pluck('firebase_token')
                        ->toArray();
                    $phoneNumbers = User::whereNotNull('phone')
                        ->pluck('phone')
                        ->toArray();
                    $jsonNotification = json_encode([]); #empty for now
                    $push_api_response = Helper::PushFirebaseNotification(
                        "AAAAmNWp5RE:APA91bET4f7TdXyaXpNCiIzjp1bk7H8y8yYtJbddzhFaU13O184U5dsvwQMa0x3JPiZnhlGBXoHFGgs8wbT7TrDP7UOn8rwBJrbBwQOvq2v_uCjBg956Q9-uhh-nrZ4NgrtLnzsVhgPV", $tokens,
                        "{$title}", "{$message}",
                        $jsonNotification, "default" #sound
                    );
                    foreach ($phoneNumbers as $phoneNumber) {
                        $sms = Helper::Post($sms_api_base_url, $sms_api_url, array(
                            'access_key' => $sms_server_key,
                            'phone' => $phoneNumber,
                            'message' => $message,
                        ));
                    }
                    // Save the alert to the database
                    DB::table('alerts')->insert([
                        'ieee' => $ieee,
                        'parameter' => "temperature",
                        'location' => 'Lilongwe Branch',
                    ]);
                }
            }

        }
    }

    /**
     * Handle the DataCentresTemp "updated" event.
     *
     * @param  \App\Models\DataCentresTemp  $dataCentresTemp
     * @return void
     */
    public function updated(DataCentresTemp $dataCentresTemp)
    {
        //
    }

    /**
     * Handle the DataCentresTemp "deleted" event.
     *
     * @param  \App\Models\DataCentresTemp  $dataCentresTemp
     * @return void
     */
    public function deleted(DataCentresTemp $dataCentresTemp)
    {
        //
    }

    /**
     * Handle the DataCentresTemp "restored" event.
     *
     * @param  \App\Models\DataCentresTemp  $dataCentresTemp
     * @return void
     */
    public function restored(DataCentresTemp $dataCentresTemp)
    {
        //
    }

    /**
     * Handle the DataCentresTemp "force deleted" event.
     *
     * @param  \App\Models\DataCentresTemp  $dataCentresTemp
     * @return void
     */
    public function forceDeleted(DataCentresTemp $dataCentresTemp)
    {
        //
    }
}
